### ISSUE TITLE
i want to train on my own dataset,can you give me any advice?

### ISSUE THREAD

**Issue by shaonianG** [filaPro/oneformer3d#102]
thank you for your reading,i have generate my custom data set in s3dis formart,and modify the config file `oneformer3d_1xb2_s3dis-area-5.py`
the code is in follow
```
_base_ = [
    'mmdet3d::_base_/default_runtime.py',
]
custom_imports = dict(imports=['oneformer3d'])

num_channels = 64
num_instance_classes = 3
num_semantic_classes = 3

model = dict(
    type='S3DISOneFormer3D',
    data_preprocessor=dict(type='Det3DDataPreprocessor'),
    in_channels=6,
    num_channels=num_channels,
    voxel_size=0.05,
    num_classes=num_instance_classes,
    min_spatial_shape=128,
    backbone=dict(
        type='SpConvUNet',
        num_planes=[num_channels * (i + 1) for i in range(5)],
        return_blocks=True),
    decoder=dict(
        type='QueryDecoder',
        num_layers=3,
        num_classes=num_instance_classes,
        num_instance_queries=400,
        num_semantic_queries=num_semantic_classes,
        num_instance_classes=num_instance_classes,
        in_channels=num_channels,
        d_model=256,
        num_heads=8,
        hidden_dim=1024,
        dropout=0.0,
        activation_fn='gelu',
        iter_pred=True,
        attn_mask=True,
        fix_attention=True,
        objectness_flag=True),
    criterion=dict(
        type='S3DISUnifiedCriterion',
        num_semantic_classes=num_semantic_classes,
        sem_criterion=dict(
            type='S3DISSemanticCriterion',
            loss_weight=5.0),
        inst_criterion=dict(
            type='InstanceCriterion',
            matcher=dict(
                type='HungarianMatcher',
                costs=[
                    dict(type='QueryClassificationCost', weight=0.5),
                    dict(type='MaskBCECost', weight=1.0),
                    dict(type='MaskDiceCost', weight=1.0)]),
            loss_weight=[0.5, 1.0, 1.0, 0.5],
            num_classes=num_instance_classes,
            non_object_weight=0.05,
            fix_dice_loss_weight=True,
            iter_matcher=True,
            fix_mean_loss=True)),
    train_cfg=dict(),
    test_cfg=dict(
        topk_insts=50,
        inst_score_thr=0.0,
        pan_score_thr=0.4,
        npoint_thr=300,
        obj_normalization=True,
        obj_normalization_thr=0.01,
        sp_score_thr=0.15,
        nms=True,
        matrix_nms_kernel='linear',
        num_sem_cls=num_semantic_classes,
        stuff_cls=[0, 1, 2, 3, 4, 5, 6, 12],
        thing_cls=[7, 8, 9, 10, 11]))

dataset_type = 'S3DISSegDataset_'
data_root = 'data/s3dis/'
data_prefix = dict(
    pts='points',
    pts_instance_mask='instance_mask',
    pts_semantic_mask='semantic_mask')

train_area = [1, 2, 3, 4, 6]
test_area = 5

train_pipeline = [
    dict(
        type='LoadPointsFromFile',
        coord_type='DEPTH',
        shift_height=False,
        use_color=True,
        load_dim=6,
        use_dim=[0, 1, 2, 3, 4, 5]),
    dict(
        type='LoadAnnotations3D',
        with_label_3d=False,
        with_bbox_3d=False,
        with_mask_3d=True,
        with_seg_3d=True),
    dict(
        type='PointSample_',
        num_points=80000),
    dict(type='PointInstClassMapping_',
        num_classes=num_instance_classes),
    dict(
        type='RandomFlip3D',
        sync_2d=False,
        flip_ratio_bev_horizontal=0.5,
        flip_ratio_bev_vertical=0.5),
    dict(
        type='GlobalRotScaleTrans',
        rot_range=[0.0, 0.0],
        scale_ratio_range=[0.9, 1.1],
        translation_std=[.1, .1, .1],
        shift_height=False),
    dict(
        type='NormalizePointsColor_',
        color_mean=[127.5, 127.5, 127.5]),
    dict(
        type='Pack3DDetInputs_',
        keys=[
            'points', 'gt_labels_3d',
            'pts_semantic_mask', 'pts_instance_mask'
        ])
]
test_pipeline = [
    dict(
        type='LoadPointsFromFile',
        coord_type='DEPTH',
        shift_height=False,
        use_color=True,
        load_dim=6,
        use_dim=[0, 1, 2, 3, 4, 5]),
    dict(
        type='LoadAnnotations3D',
        with_bbox_3d=False,
        with_label_3d=False,
        with_mask_3d=True,
        with_seg_3d=True),
    dict(
        type='MultiScaleFlipAug3D',
        img_scale=(1333, 800),
        pts_scale_ratio=1,
        flip=False,
        transforms=[
            dict(
                type='NormalizePointsColor_',
                color_mean=[127.5, 127.5, 127.5])]),
    dict(type='Pack3DDetInputs_', keys=['points'])
]

train_dataloader = dict(
    batch_size=1,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
            type='ConcatDataset',
            datasets=([
                dict(
                    type=dataset_type,
                    data_root=data_root,
                    ann_file=f's3dis_infos_Area_{i}.pkl',
                    pipeline=train_pipeline,
                    filter_empty_gt=True,
                    data_prefix=data_prefix,
                    box_type_3d='Depth',
                    backend_args=None) for i in train_area])))

val_dataloader = dict(
    batch_size=1,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file=f's3dis_infos_Area_{test_area}.pkl',
        pipeline=test_pipeline,
        test_mode=True,
        data_prefix=data_prefix,
        box_type_3d='Depth',
        backend_args=None))
test_dataloader = val_dataloader

class_names = [
    'leaf', 'branch', 'litchi']
label2cat = {i: name for i, name in enumerate(class_names)}
metric_meta = dict(
    label2cat=label2cat,
    ignore_index=[num_semantic_classes],
    classes=class_names,
    dataset_name='S3DIS')
sem_mapping = [0, 1, 2]

val_evaluator = dict(
    type='UnifiedSegMetric',
    stuff_class_inds=[0, 1],
    thing_class_inds=[2],
    min_num_points=1,
    id_offset=2**16,
    sem_mapping=sem_mapping,
    inst_mapping=sem_mapping,
    submission_prefix_semantic=None,
    submission_prefix_instance=None,
    metric_meta=metric_meta)
test_evaluator = val_evaluator

optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='AdamW', lr=0.0001, weight_decay=0.05),
    clip_grad=dict(max_norm=10, norm_type=2))
param_scheduler = dict(type='PolyLR', begin=0, end=512, power=0.9)

custom_hooks = [dict(type='EmptyCacheHook', after_iter=True)]
default_hooks = dict(
    checkpoint=dict(
        interval=16,
        max_keep_ckpts=1,
        save_best=['all_ap_50%', 'miou'],
        rule='greater'))

load_from = 'work_dirs/tmp/instance-only-oneformer3d_1xb2_scannet-and-structured3d.pth'

train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=512, val_interval=16)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')
```
but when i run `train.py` it still show old class name
```
+----------+--------+
| category | number |
+----------+--------+
| ceiling  | 0      |
| floor    | 0      |
| wall     | 0      |
| beam     | 0      |
| column   | 0      |
| window   | 0      |
| door     | 0      |
| table    | 0      |
| chair    | 0      |
| sofa     | 0      |
| bookcase | 0      |
| board    | 0      |
| clutter  | 0      |
+----------+--------+
12/04 12:24:13 - mmengine - INFO - ------------------------------
12/04 12:24:13 - mmengine - INFO - The length of the dataset: 1
12/04 12:24:13 - mmengine - INFO - The number of instances per category in the dataset:
+----------+--------+
| category | number |
+----------+--------+
| ceiling  | 0      |
| floor    | 0      |
| wall     | 0      |
| beam     | 0      |
| column   | 0      |
| window   | 0      |
| door     | 0      |
| table    | 0      |
| chair    | 0      |
| sofa     | 0      |
| bookcase | 0      |
| board    | 0      |
| clutter  | 0      |
+----------+--------+
12/04 12:24:13 - mmengine - INFO - ------------------------------
12/04 12:24:13 - mmengine - INFO - The length of the dataset: 1
12/04 12:24:13 - mmengine - INFO - The number of instances per category in the dataset:
+----------+--------+
| category | number |
+----------+--------+
| ceiling  | 0      |
| floor    | 0      |
| wall     | 0      |
| beam     | 0      |
| column   | 0      |
| window   | 0      |
| door     | 0      |
| table    | 0      |
| chair    | 0      |
| sofa     | 0      |
| bookcase | 0      |
| board    | 0      |
| clutter  | 0      |
+----------+--------+
12/04 12:24:14 - mmengine - INFO - ------------------------------
12/04 12:24:14 - mmengine - INFO - The length of the dataset: 2
12/04 12:24:14 - mmengine - INFO - The number of instances per category in the dataset:
+----------+--------+
| category | number |
+----------+--------+
| ceiling  | 0      |
| floor    | 0      |
| wall     | 0      |
| beam     | 0      |
| column   | 0      |
| window   | 0      |
| door     | 0      |
| table    | 0      |
| chair    | 0      |
| sofa     | 0      |
| bookcase | 0      |
| board    | 0      |
| clutter  | 0      |
+----------+--------+
12/04 12:24:14 - mmengine - WARNING - The prefix is not set in metric class UnifiedSegMetric.
Loads checkpoint by local backend from path: work_dirs/tmp/instance-only-oneformer3d_1xb2_scannet-and-structured3d.pth`
and finally i get this error
`12/05 01:13:48 - mmengine - INFO - Load checkpoint from work_dirs/tmp/instance-only-oneformer3d_1xb2_scannet-and-structured3d.pth
12/05 01:13:48 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
12/05 01:13:48 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
12/05 01:13:48 - mmengine - INFO - Checkpoints will be saved to /workspace/work_dirs/oneformer3d_1xb2_s3dis-area-5.
Traceback (most recent call last):
  File "/workspace/tools/train.py", line 139, in <module>
    main()
  File "/workspace/tools/train.py", line 135, in main
    runner.train()
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1721, in train
    model = self.train_loop.run()  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/loops.py", line 111, in run_epoch
    for idx, data_batch in enumerate(self.dataloader):
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
Exception: Caught Exception in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.10/site-packages/mmengine/dataset/dataset_wrapper.py", line 159, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/opt/conda/lib/python3.10/site-packages/mmengine/dataset/base_dataset.py", line 421, in __getitem__
    raise Exception(f'Cannot find valid image after {self.max_refetch}! '
Exception: Cannot find valid image after 1000! Please check your image path and pipeline
```

can you tell me where i should modify?
and if i train my data set,it has three slasses,completely different with s3dis,so i can't use the pretrain model(you mentioned in here⬇️)?
`S3DIS
For S3DIS we present the model with [SpConv](https://github.com/traveller59/spconv) backbone, w/o superpoint pooling, w/o query selection, and with separate semantic queries. Backbone is pretrained on Structured3D and ScanNet. It can be [downloaded](https://github.com/oneformer3d/oneformer3d/releases/download/v1.0/instance-only-oneformer3d_1xb2_scannet-and-structured3d.pth) and put to work_dirs/tmp before training or trained with our code. We train the model on Areas 1, 2, 3, 4, 6 and test on Area 5. To change this split feel free to modify train_area and test_area parameters in config.`

**Comment by filaPro** [comment]
In your config I see `dataset_type = 'S3DISSegDataset_'`. I think you should make your own dataset class similar to this `S3DISSegDataset_`.

**Comment by shaonianG** [comment]
> In your config I see `dataset_type = 'S3DISSegDataset_'`. I think you should make your own dataset class similar to this `S3DISSegDataset_`.

yes，i have build my own data set
here is the struct of filefolder
```
D:.
├─Area_1
│  └─litchibranch_1
│      │  litchibranch_1.txt
│      │
│      └─Annotations
│              branch_1.txt
│              litchi_1.txt
│              litchi_2.txt
│
├─Area_2
│  └─litchibranch_1
│      │  litchibranch_1.txt
│      │
│      └─Annotations
│              branch_1.txt
│              leaf_1.txt
│              litchi_1.txt
│              litchi_2.txt
│              litchi_3.txt
│              litchi_4.txt
│              litchi_5.txt
│
├─Area_3
│  └─litchibranch_1
│      │  litchibranch_1.txt
│      │
│      └─Annotations
│              branch_1.txt
│              litchi_1.txt
│              litchi_2.txt
│
├─Area_4
│  └─litchibranch_1
│      │  litchibranch_1.txt
│      │
│      └─Annotations
│              branch_1.txt
│              litchi_1.txt
│              litchi_2.txt
│
├─Area_5
│  ├─litchibranch_1
│  │  │  litchibranch_1.txt
│  │  │
│  │  └─Annotations
│  │          branch_1.txt
│  │          leaf_1.txt
│  │          litchi_1.txt
│  │          litchi_2.txt
│  │          litchi_3.txt
│  │          litchi_4.txt
│  │          litchi_5.txt
│  │
│  └─litchibranch_2
│      │  litchibranch_2.txt
│      │
│      └─Annotations
│              branch_1.txt
│              litchi_1.txt
│              litchi_2.txt
│              litchi_3.txt
│              litchi_4.txt
│              litchi_5.txt
│
└─Area_6
    └─litchibranch_1
        │  litchibranch_1.txt
        │
        └─Annotations
                branch_1.txt
                litchi_1.txt
                litchi_2.txt
                litchi_3.txt
                litchi_4.txt
```
and i also generate the data set follow mmdet3d

```
─s3dis
│  │  collect_indoor3d_data.py
│  │  indoor3d_util.py
│  │  README.md
│  │  s3dis_infos_Area_1.pkl
│  │  s3dis_infos_Area_2.pkl
│  │  s3dis_infos_Area_3.pkl
│  │  s3dis_infos_Area_4.pkl
│  │  s3dis_infos_Area_5.pkl
│  │  s3dis_infos_Area_6.pkl
│  │
│  ├─instance_mask
│  │      Area_1_litchibranch_1.bin
│  │      Area_2_litchibranch_1.bin
│  │      Area_3_litchibranch_1.bin
│  │      Area_4_litchibranch_1.bin
│  │      Area_5_litchibranch_1.bin
│  │      Area_5_litchibranch_2.bin
│  │      Area_6_litchibranch_1.bin
│  │
│  ├─meta_data
│  │      anno_paths.txt
│  │      class_names.txt
│  │
│  ├─points
│  │      Area_1_litchibranch_1.bin
│  │      Area_2_litchibranch_1.bin
│  │      Area_3_litchibranch_1.bin
│  │      Area_4_litchibranch_1.bin
│  │      Area_5_litchibranch_1.bin
│  │      Area_5_litchibranch_2.bin
│  │      Area_6_litchibranch_1.bin
│  │
│  ├─s3dis_data
│  │  │  Area_1_litchibranch_1_ins_label.npy
│  │  │  Area_1_litchibranch_1_point.npy
│  │  │  Area_1_litchibranch_1_sem_label.npy
│  │  │  Area_2_litchibranch_1_ins_label.npy
│  │  │  Area_2_litchibranch_1_point.npy
│  │  │  Area_2_litchibranch_1_sem_label.npy
│  │  │  Area_3_litchibranch_1_ins_label.npy
│  │  │  Area_3_litchibranch_1_point.npy
│  │  │  Area_3_litchibranch_1_sem_label.npy
│  │  │  Area_4_litchibranch_1_ins_label.npy
│  │  │  Area_4_litchibranch_1_point.npy
│  │  │  Area_4_litchibranch_1_sem_label.npy
│  │  │  Area_5_litchibranch_1_ins_label.npy
│  │  │  Area_5_litchibranch_1_point.npy
│  │  │  Area_5_litchibranch_1_sem_label.npy
│  │  │  Area_5_litchibranch_2_ins_label.npy
│  │  │  Area_5_litchibranch_2_point.npy
│  │  │  Area_5_litchibranch_2_sem_label.npy
│  │  │  Area_6_litchibranch_1_ins_label.npy
│  │  │  Area_6_litchibranch_1_point.npy
│  │  │  Area_6_litchibranch_1_sem_label.npy
│  │  │
│  │  └─Stanford3dDataset_v1.2_Aligned_Version
│  ├─seg_info
│  │      Area_1_label_weight.npy
│  │      Area_1_resampled_scene_idxs.npy
│  │      Area_2_label_weight.npy
│  │      Area_2_resampled_scene_idxs.npy
│  │      Area_3_label_weight.npy
│  │      Area_3_resampled_scene_idxs.npy
│  │      Area_4_label_weight.npy
│  │      Area_4_resampled_scene_idxs.npy
│  │      Area_5_label_weight.npy
│  │      Area_5_resampled_scene_idxs.npy
│  │      Area_6_label_weight.npy
│  │      Area_6_resampled_scene_idxs.npy
│  │
│  ├─semantic_mask
│  │      Area_1_litchibranch_1.bin
│  │      Area_2_litchibranch_1.bin
│  │      Area_3_litchibranch_1.bin
│  │      Area_4_litchibranch_1.bin
│  │      Area_5_litchibranch_1.bin
│  │      Area_5_litchibranch_2.bin
│  │      Area_6_litchibranch_1.bin
│  │
│  ├─Stanford3dDataset_v1.2_Aligned_Version
│  │  ├─Area_1
│  │  │  └─litchibranch_1
│  │  │      │  litchibranch_1.txt
│  │  │      │
│  │  │      └─Annotations
│  │  │              branch_1.txt
│  │  │              litchi_1.txt
│  │  │              litchi_2.txt
│  │  │
│  │  ├─Area_2
│  │  │  └─litchibranch_1
│  │  │      │  litchibranch_1.txt
│  │  │      │
│  │  │      └─Annotations
│  │  │              branch_1.txt
│  │  │              leaf_1.txt
│  │  │              litchi_1.txt
│  │  │              litchi_2.txt
│  │  │              litchi_3.txt
│  │  │              litchi_4.txt
│  │  │              litchi_5.txt
│  │  │
│  │  ├─Area_3
│  │  │  └─litchibranch_1
│  │  │      │  litchibranch_1.txt
│  │  │      │
│  │  │      └─Annotations
│  │  │              branch_1.txt
│  │  │              litchi_1.txt
│  │  │              litchi_2.txt
│  │  │
│  │  ├─Area_4
│  │  │  └─litchibranch_1
│  │  │      │  litchibranch_1.txt
│  │  │      │
│  │  │      └─Annotations
│  │  │              branch_1.txt
│  │  │              litchi_1.txt
│  │  │              litchi_2.txt
│  │  │
│  │  ├─Area_5
│  │  │  ├─litchibranch_1
│  │  │  │  │  litchibranch_1.txt
│  │  │  │  │
│  │  │  │  └─Annotations
│  │  │  │          branch_1.txt
│  │  │  │          leaf_1.txt
│  │  │  │          litchi_1.txt
│  │  │  │          litchi_2.txt
│  │  │  │          litchi_3.txt
│  │  │  │          litchi_4.txt
│  │  │  │          litchi_5.txt
│  │  │  │
│  │  │  └─litchibranch_2
│  │  │      │  litchibranch_2.txt
│  │  │      │
│  │  │      └─Annotations
│  │  │              branch_1.txt
│  │  │              litchi_1.txt
│  │  │              litchi_2.txt
│  │  │              litchi_3.txt
│  │  │              litchi_4.txt
│  │  │              litchi_5.txt
│  │  │
│  │  └─Area_6
│  │      └─litchibranch_1
│  │          │  litchibranch_1.txt
│  │          │
│  │          └─Annotations
│  │                  branch_1.txt
│  │                  litchi_1.txt
│  │                  litchi_2.txt
│  │                  litchi_3.txt
│  │                  litchi_4.txt
│  │
│  └─__pycache__
│          indoor3d_util.cpython-38.pyc
│
└─Stanford3dDataset_v1.2_Aligned_Version
    ├─Area_1
    │  └─litchibranch_1
    │      │  litchibranch_1.txt
    │      │
    │      └─Annotations
    │              branch_1.txt
    │              litchi_1.txt
    │              litchi_2.txt
    │
    ├─Area_2
    │  └─litchibranch_1
    │      │  litchibranch_1.txt
    │      │
    │      └─Annotations
    │              branch_1.txt
    │              leaf_1.txt
    │              litchi_1.txt
    │              litchi_2.txt
    │              litchi_3.txt
    │              litchi_4.txt
    │              litchi_5.txt
    │
    ├─Area_3
    │  └─litchibranch_1
    │      │  litchibranch_1.txt
    │      │
    │      └─Annotations
    │              branch_1.txt
    │              litchi_1.txt
    │              litchi_2.txt
    │
    ├─Area_4
    │  └─litchibranch_1
    │      │  litchibranch_1.txt
    │      │
    │      └─Annotations
    │              branch_1.txt
    │              litchi_1.txt
    │              litchi_2.txt
    │
    ├─Area_5
    │  ├─litchibranch_1
    │  │  │  litchibranch_1.txt
    │  │  │
    │  │  └─Annotations
    │  │          branch_1.txt
    │      └─Annotations
    │              branch_1.txt
    │              litchi_1.txt
    │              litchi_2.txt
    │              litchi_3.txt
    │              litchi_4.txt
    │              litchi_5.txt
    │
    └─Area_6
        └─litchibranch_1
            │  litchibranch_1.txt
            │
            └─Annotations
                    branch_1.txt
                    litchi_1.txt
                    litchi_2.txt
                    litchi_3.txt
                    litchi_4.txt
```

**Comment by filaPro** [comment]
Why did you split your dataset to 6 areas? It is not necessary. Just make your own dataset class `YourDataset(S3DISDataset)`, then check that `dataset = YourDataset(); for batch in dataset: print(batch)` returns correct batches with just 3 categories, and then put `YourDataset` to config, removing `S3DISDataset_`, areas, `ConcatDataset` etc.

**Comment by filaPro** [comment]
This error `Exception: Cannot find valid image after 1000! Please check your image path and pipeline` means that your dataset + our preprocessing pipeline return 0 valid instances for each scene. I think you missed with label ids somewhere.

**Comment by shaonianG** [comment]
> This error `Exception: Cannot find valid image after 1000! Please check your image path and pipeline` means that your dataset + our preprocessing pipeline return 0 valid instances for each scene. I think you missed with label ids somewhere.
 ### firstly,merry holiday!
thank you for you advise，i check the point cloud between mine and s3dis,find that my point cloud have nie cols
![image](https://github.com/user-attachments/assets/d02c298b-84fb-4094-83d4-7d13bfc0106d)
my point cloud file, xyz、rgb and nx，ny,nz(Normal vector)
![image](https://github.com/user-attachments/assets/84a44cc8-8f43-4f4d-a4b7-9a261ba755a7)
s3dis point cloud, xyz、rgb

after solver these problem,i have another question hope you can help me
first,i want to know how to change this valve
self.valid_class_ids = self.dataset_meta['seg_valid_class_ids']
[https://github.com/filaPro/oneformer3d/blob/main/oneformer3d/unified_metric.py#L67](url)
![image](https://github.com/user-attachments/assets/eaf9069d-8798-4c2d-b07d-f20c92b25bc9)
i need this value to be [0,1,2],but did't find how to modify it in config file
to run train.py, i have to modify it mannually...by add this code
```
        if len(self.dataset_meta['seg_valid_class_ids']) != 3:
            self.dataset_meta['seg_valid_class_ids'] = list(self.dataset_meta['seg_valid_class_ids'])
            # insert 0
            self.dataset_meta['seg_valid_class_ids'].insert(0, 0)

            self.dataset_meta['seg_valid_class_ids'] = tuple(self.dataset_meta['seg_valid_class_ids'])

            self.valid_class_ids = self.dataset_meta['seg_valid_class_ids']
```

second,i train on my own dataset,it has a high score in val epoch,my data set is small.so it will over fitting in 16 epoch
my dataset have 72 point cloud

```
+---------+---------+---------+--------+-----------+----------+
| classes | AP_0.25 | AP_0.50 | AP     | Prec_0.50 | Rec_0.50 |
+---------+---------+---------+--------+-----------+----------+
| leaf    | 0.6112  | 0.3891  | 0.2343 | 0.6154    | 0.3478   |
| branch  | 0.6667  | 0.6667  | 0.6006 | 1.0000    | 0.6667   |
| litchi  | 0.9448  | 0.8897  | 0.7660 | 0.9444    | 0.8718   |
+---------+---------+---------+--------+-----------+----------+
| Overall | 0.7409  | 0.6485  | 0.5336 | 0.8533    | 0.6288   |
+---------+---------+---------+--------+-----------+----------+
```

but when i run test.py ,the score is very low,val and test is in same area,why this score have such different?
```
+---------+---------+---------+--------+-----------+----------+
| classes | AP_0.25 | AP_0.50 | AP     | Prec_0.50 | Rec_0.50 |
+---------+---------+---------+--------+-----------+----------+
| leaf    | 0.0039  | 0.0000  | 0.0000 | 0.0000    | 0.0000   |
| branch  | 0.0569  | 0.0046  | 0.0015 | 0.1111    | 0.0833   |
| litchi  | 0.0226  | 0.0001  | 0.0000 | 0.0109    | 0.0256   |
+---------+---------+---------+--------+-----------+----------+
| Overall | 0.0278  | 0.0016  | 0.0005 | 0.0407    | 0.0363   |
+---------+---------+---------+--------+-----------+----------+
```
looking forward to your reply,and thank you for your great work again!

**Comment by filaPro** [comment]
Are your test and val sets equal? Did you reshape checkpoint between test and val with `fix_spconv_checkpoint.py` according to our readme?

**Comment by shaonianG** [comment]
> Are your test and val sets equal? Did you reshape checkpoint between test and val with `fix_spconv_checkpoint.py` according to our readme?

yes,i forget this step,after fix step,model get a correct score in test
