### ISSUE TITLE
How can I visualize the test results?

### ISSUE THREAD

**Issue by clawCa** [filaPro/oneformer3d#81]
Thank you for your outstanding work.
I converted my dataset using the S3DIS preprocessing script and trained the model. After converting the model with fix_spconv_checkpoint.py, the test program gives an error when I select any parameter for the --task(choices=[ 'mono_det', 'multi-view_det', 'lidar_det', 'lidar_seg', 'multi-modality_det' ],). It seems this parameter is necessary for visualization.

For example, selecting **--task lidar_seg** , results in the following error:
Traceback (most recent call last):
  File "/home/docker_data/oneformer3d-main/tools/test.py", line 149, in <module>
    main()
  File "/home/docker_data/oneformer3d-main/tools/test.py", line 145, in main
    runner.test()
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1767, in test
    metrics = self.test_loop.run()  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/loops.py", line 435, in run
    self.run_iter(idx, data_batch)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/loops.py", line 456, in run_iter
    self.runner.call_hook(
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1785, in call_hook
    raise TypeError(f'{e} in {hook}') from None
TypeError: Visualizer.add_datasample() got an unexpected keyword argument 'vis_task' in <mmdet3d.engine.hooks.visualization_hook.Det3DVisualizationHook object at 0x7f89bab38460>

**Comment by filaPro** [comment]
Hi @clawCa ,
Unfortunately we don't support visualization in this repo, please see #57.
