### ISSUE TITLE
something wrong with create_data.py

### ISSUE THREAD

**Issue by shaonianG** [filaPro/oneformer3d#83]
i have download the scannet data set,then i try to run create_data.py to build train data,but this program show me this message

`Traceback (most recent call last):
  File "tools/create_data.py", line 51, in <module>
    scannet_data_prep(
  File "tools/create_data.py", line 18, in scannet_data_prep
    create_indoor_info_file(
  File "D:\project\python\oneformer3d\tools\indoor_converter.py", line 54, in create_indoor_info_file
    infos_train = train_dataset.get_infos(
  File "D:\project\python\oneformer3d\tools\scannet_data_utils.py", line 281, in get_infos
    return list(infos)
  File "D:\software\anaconda3\envs\oneformer3d\lib\concurrent\futures\_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "D:\software\anaconda3\envs\oneformer3d\lib\concurrent\futures\_base.py", line 437, in result
    return self.__get_result()
  File "D:\software\anaconda3\envs\oneformer3d\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "D:\software\anaconda3\envs\oneformer3d\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\project\python\oneformer3d\tools\scannet_data_utils.py", line 185, in process_single_scene
    points = np.load(pts_filename)
  File "D:\software\anaconda3\envs\oneformer3d\lib\site-packages\numpy\lib\npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '.\\data\\scannet\\scannet_instance_data\\scene0191_00_vert.npy`
i want know how to solve this problem,thank you

**Comment by shaonianG** [comment]
i execute this in terminal
`python tools/create_data.py scannet --root-path .\data\scannet\ --out-dir .\data\scannet\ --extra-tag scannet
`

**Comment by col14m** [comment]
Please follow the instruction provided [here](https://github.com/filaPro/oneformer3d/tree/main/data/scannet#:~:text=The%20overall%20process%20for%20ScanNet%20could%20be%20achieved%20through%20the%20following%20script) and run `python batch_load_scannet_data.py` before.

**Comment by shaonianG** [comment]
thank you for your reply,
`python batch_load_scannet_data.py`show that
`ModuleNotFoundError: No module named 'segmentator'
`
is anything worng with wy install about [mmdetection3d]?

**Comment by filaPro** [comment]
Please follow installation process from our Dockerfile including this [line](https://github.com/filaPro/oneformer3d/blob/main/Dockerfile#L29) to install `segmentor`.

**Comment by shaonianG** [comment]
thank you for you help，finally i decide to use s3dis data set and successfully prepared this data set
then i follow the
`Backbone is pretrained on Structured3D and ScanNet. It can be [downloaded](https://github.com/oneformer3d/oneformer3d/releases/download/v1.0/instance-only-oneformer3d_1xb2_scannet-and-structured3d.pth) and put to work_dirs/tmp before training or trained`
download this model and put it in
![image](https://github.com/user-attachments/assets/13d13745-0f79-4a0d-8245-e4a6fd10c4dd)
i run this line and get this error
`# pre-train
python tools/train.py configs/instance-only-oneformer3d_1xb2_scannet-and-structured3d.py`

`Traceback (most recent call last):
  File "tools/train.py", line 138, in <module>
    main()
  File "tools/train.py", line 127, in main
    runner = Runner.from_cfg(cfg)
  File "D:\software\anaconda3\envs\oneformer3d\lib\site-packages\mmengine\runner\runner.py", line 462, in from_cfg
    runner = cls(
  File "D:\software\anaconda3\envs\oneformer3d\lib\site-packages\mmengine\runner\runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "D:\software\anaconda3\envs\oneformer3d\lib\site-packages\mmengine\runner\runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "D:\software\anaconda3\envs\oneformer3d\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\software\anaconda3\envs\oneformer3d\lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\software\anaconda3\envs\oneformer3d\lib\site-packages\mmengine\registry\build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'InstanceOnlyOneFormer3D is not in the mmdet3d::model registry. Please check whether the value of `InstanceOnlyOneFormer3D` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'  `
i read this code and mmdected3d's document but can't solve this error
looking for you help,thank you!
