### ISSUE TITLE
When I use "python tools/train.py configs/instance-only-oneformer3d_1xb2_scannet-and-structured3d.py"，it gives me an error

### ISSUE THREAD

**Issue by yangke111** [filaPro/oneformer3d#95]
我的报错信息如下：

11/25 16:48:43 - mmengine - INFO - Adafactor is already registered in optimizer at torch.optim. Registration ignored.
/home/y402/anaconda3/envs/oneformer3d/lib/python3.11/site-packages/mmengine/optim/optimizer/zero_optimizer.py:11: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
/home/y402/anaconda3/envs/oneformer3d/lib/python3.11/site-packages/spconv/pytorch/functional.py:47: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  _TORCH_CUSTOM_FWD = amp.custom_fwd(cast_inputs=torch.float16)
/home/y402/anaconda3/envs/oneformer3d/lib/python3.11/site-packages/spconv/pytorch/functional.py:96: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @_TORCH_CUSTOM_BWD
/home/y402/anaconda3/envs/oneformer3d/lib/python3.11/site-packages/spconv/pytorch/functional.py:162: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @_TORCH_CUSTOM_BWD
/home/y402/anaconda3/envs/oneformer3d/lib/python3.11/site-packages/spconv/pytorch/functional.py:242: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @_TORCH_CUSTOM_BWD
/home/y402/anaconda3/envs/oneformer3d/lib/python3.11/site-packages/spconv/pytorch/functional.py:331: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @_TORCH_CUSTOM_BWD
/home/y402/anaconda3/envs/oneformer3d/lib/python3.11/site-packages/spconv/pytorch/functional.py:368: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @_TORCH_CUSTOM_BWD
/home/y402/anaconda3/envs/oneformer3d/lib/python3.11/site-packages/spconv/pytorch/functional.py:388: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @_TORCH_CUSTOM_BWD
/home/y402/anaconda3/envs/oneformer3d/lib/python3.11/site-packages/spconv/pytorch/functional.py:411: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @_TORCH_CUSTOM_BWD
Traceback (most recent call last):
  File "/home/y402/anaconda3/envs/oneformer3d/lib/python3.11/site-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
                   ^^^^^^^^^^^^^^^^^^
  File "/home/y402/anaconda3/envs/oneformer3d/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/y402/oneformer3d/oneformer3d/__init__.py", line 1, in <module>
    from .oneformer3d import (
  File "/home/y402/oneformer3d/oneformer3d/oneformer3d.py", line 5, in <module>
    import MinkowskiEngine as ME
ModuleNotFoundError: No module named 'MinkowskiEngine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/y402/anaconda3/envs/oneformer3d/lib/python3.11/site-packages/mmengine/config/config.py", line 466, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/y402/anaconda3/envs/oneformer3d/lib/python3.11/site-packages/mmengine/utils/misc.py", line 84, in import_modules_from_strings
    raise ImportError(f'Failed to import {imp}')
ImportError: Failed to import oneformer3d

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/y402/oneformer3d/tools/train.py", line 136, in <module>
    main()
  File "/home/y402/oneformer3d/tools/train.py", line 68, in main
    cfg = Config.fromfile(args.config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/y402/anaconda3/envs/oneformer3d/lib/python3.11/site-packages/mmengine/config/config.py", line 478, in fromfile
    raise ImportError(err_msg) from e
ImportError: Failed to import custom modules from {'imports': ['oneformer3d']}, the current sys.path is: 
    /home/y402/oneformer3d/tools
    /home/y402/oneformer3d
    /home/y402
    /home/y402/anaconda3/envs/oneformer3d/lib/python311.zip
    /home/y402/anaconda3/envs/oneformer3d/lib/python3.11
    /home/y402/anaconda3/envs/oneformer3d/lib/python3.11/lib-dynload
    /home/y402/anaconda3/envs/oneformer3d/lib/python3.11/site-packages
    /tmp/tmpkpeb67xi
You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module

并且我使用了export PYTHONPATH=/path/to/directory，也没有效果，报同样的错误

**Comment by filaPro** [comment]
> ModuleNotFoundError: No module named 'MinkowskiEngine'

did you install minkowskiengine?

**Comment by ImageKai** [comment]
I have same issue as above.

**Comment by chinagalaxy2002** [comment]
> I have same issue as above.我有与上面相同的问题。
Did you solve the last error? It is the error related to the inability to import and syspath
